# Generated by Django 3.0.1 on 2019-12-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=800)),
                ('lastname', models.CharField(max_length=800)),
                ('emp_id', models.IntegerField()),
            ],
        ),
    ]
